# Nginx configuration template for List Manager

location __PATH__ {

    # Path protection is handled by YunoHost in the main domain config

    # Proxy requests to the Gunicorn backend
    proxy_pass http://127.0.0.1:__PORT__; # __PORT__ is automatically assigned by YunoHost
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;

    # Websocket support (if needed in the future, not strictly necessary for this app now)
    # proxy_http_version 1.1;
    # proxy_set_header Upgrade $http_upgrade;
    # proxy_set_header Connection "upgrade";

    # Include SSOWAT user panel.
    include conf.d/yunohost_panel.conf.inc;
}

